name: Fetch Weather Screenshot

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes (UTC)
  workflow_dispatch:        # Manual trigger option

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright pillow
          playwright install --with-deps

      - name: Run script
        run: python fetch_weather_image.py

      - name: Commit and push updated image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add bg_ss00.png
          git commit -m "Update Kindle screenshot" || echo "No changes"
          git push
